name = "wallet-management"
compatibility_date = "2024-05-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npx @cloudflare/next-on-pages@1"

[env.production]
# Add your production environment variables here in the Cloudflare dashboard instead
# DATABASE_URL = "..."
# AUTH_SECRET = "..."
